export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const UPDATE_USER_PHOTO_LOADING = "UPDATE_USER_PHOTO_LOADING";
export const UPDATE_USER_PHOTO_SUCCESS = "UPDATE_USER_PHOTO_SUCCESS";
export const UPDATE_USER_PHOTO_FAILED = "UPDATE_USER_PHOTO_FAILED";

export const AUTH_CHECKING_FINISH = "AUTH_CHECKING_FINISH";
export const LOGOUT_USER_FINISH = "LOGOUT_USER_FINISH";
